name: vivagua
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_map:
  fluro:
  charts_flutter:
  charts_common:
  firebase_core:
  cloud_firestore:
  cloud_functions:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  intl:
  carousel_pro: ^0.0.13
  mailer2: ^1.2.4
  async: ^2.2.0
  pdf: ^1.3.7
  smooth_star_rating: 1.0.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   
    - assets/
    - assets/img/
    - assets/avatars/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Overpass Regular
      fonts:
        - asset: fonts/Overpass-Regular.ttf
    - family: Overpass SemiBold
      fonts:
        - asset: fonts/Overpass-SemiBold.ttf
          weight: 600
    - family: Overpass ExtraLight
      fonts:
        - asset: fonts/Overpass-ExtraLight.ttf
          weight: 200
    - family: YanoneKaffeesatz Bold
      fonts:
        - asset: fonts/YanoneKaffeesatz-Bold.ttf
          weight: 700
    - family: YanoneKaffeesatz Regular
      fonts:
        - asset: fonts/YanoneKaffeesatz-Regular.ttf
          weight: 400
    - family: YanoneKaffeesatz Light
      fonts:
        - asset: fonts/YanoneKaffeesatz-Light.ttf
          weight: 300

  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
